[package]
name = "msg-filter"
version = "0.1.3"
authors = ["aRandomGithubUser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
json = "0.12.4"
regex = "1.3.9"
censor = "0.1.1"